In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [5]:
X_train,X_test,Y_train,Y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [6]:
scaller=StandardScaler()
X_train=scaller.fit_transform(X_train)
X_test=scaller.transform(X_test)

In [7]:
X_train

array([[ 1.67716182,  2.07144135,  1.58652081, ...,  0.69181328,
        -0.54306039, -0.9786102 ],
       [ 0.01528741,  0.28314153,  0.01115554, ...,  0.25944804,
        -0.60399485, -0.30889458],
       [ 0.55616728,  0.31788829,  0.64836825, ...,  1.35756597,
         1.27535243,  1.644854  ],
       ...,
       [ 0.53935236,  0.07929388,  0.48591759, ...,  0.53023734,
        -0.41798437, -1.11573461],
       [-0.78622369, -0.16161697, -0.78688333, ..., -0.46584838,
         0.23946647, -0.89852954],
       [-0.13604685, -0.04116154, -0.10865182, ...,  0.36118104,
        -0.26725174,  0.2291816 ]], shape=(455, 30))

In [8]:
Y_train

565    M
476    B
17     M
44     M
265    M
      ..
472    B
97     B
75     M
515    B
423    B
Name: diagnosis, Length: 455, dtype: object

In [9]:
encoder=LabelEncoder()
Y_train=encoder.fit_transform(Y_train)
Y_test=encoder.transform(Y_test)

In [23]:
Y_test

array([1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0])

In [24]:
x_test_tensor=torch.from_numpy(X_test)
y_test_tensor=torch.from_numpy(Y_test)
x_train_tensor=torch.from_numpy(X_train)
y_train_tensor=torch.from_numpy(Y_train)

In [25]:
class simplePerceptron():
    def __init__(self,x):
        self.weights= torch.rand(x.shape[1],1,dtype=torch.float64,requires_grad=True)
        self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)
    def forward(self,x):
        z=torch.matmul(x,self.weights)+self.bias
        ypred = torch.sigmoid(z)
        return ypred
    def loss_function(self, ypred, y):
        epsilon = 1e-7
        ypred = torch.clamp(ypred, epsilon, 1 - epsilon)
        loss = -(y_train_tensor * torch.log(ypred) + (1 - y_train_tensor) * torch.log(1 - ypred)).mean()
        return loss

In [39]:
lr=0.1
epochs=25
print(x_train_tensor)

tensor([[ 1.6772,  2.0714,  1.5865,  ...,  0.6918, -0.5431, -0.9786],
        [ 0.0153,  0.2831,  0.0112,  ...,  0.2594, -0.6040, -0.3089],
        [ 0.5562,  0.3179,  0.6484,  ...,  1.3576,  1.2754,  1.6449],
        ...,
        [ 0.5394,  0.0793,  0.4859,  ...,  0.5302, -0.4180, -1.1157],
        [-0.7862, -0.1616, -0.7869,  ..., -0.4658,  0.2395, -0.8985],
        [-0.1360, -0.0412, -0.1087,  ...,  0.3612, -0.2673,  0.2292]],
       dtype=torch.float64)


In [27]:
model=simplePerceptron(x_train_tensor)

In [28]:
print(model.weights)

tensor([[0.5446],
        [0.5473],
        [0.4775],
        [0.4108],
        [0.0932],
        [0.1187],
        [0.6857],
        [0.5285],
        [0.6237],
        [0.7115],
        [0.6884],
        [0.8330],
        [0.3765],
        [0.3022],
        [0.1641],
        [0.8112],
        [0.8685],
        [0.3834],
        [0.0131],
        [0.9389],
        [0.3832],
        [0.6262],
        [0.0403],
        [0.5004],
        [0.1176],
        [0.2802],
        [0.3853],
        [0.9567],
        [0.8462],
        [0.7826]], dtype=torch.float64, requires_grad=True)


In [29]:
print(model)

In [42]:
for epoch in range(epochs):
    ypred = model.forward(x_train_tensor)
    loss= model.loss_function(ypred,y_train_tensor)
    loss.backward()
    with torch.no_grad():
        model.weights-=lr*model.weights.grad
        model.bias-=model.bias.grad
    model.weights.grad.zero_()
    model.bias.grad.zero_()
    print(f'for epoch:{epoch+1} loss is {loss.item()}')

for epoch:1 loss is 0.6960079860306877
for epoch:2 loss is 0.6949723430165792
for epoch:3 loss is 0.6940085421647568
for epoch:4 loss is 0.6931098242761685
for epoch:5 loss is 0.6922701477327893
for epoch:6 loss is 0.6914841041172645
for epoch:7 loss is 0.6907468448590386
for epoch:8 loss is 0.6900540173364873
for epoch:9 loss is 0.6894017090943267
for epoch:10 loss is 0.6887863990346028
for epoch:11 loss is 0.6882049146105085
for epoch:12 loss is 0.6876543941981283
for epoch:13 loss is 0.6871322539450194
for epoch:14 loss is 0.6866361584992638
for epoch:15 loss is 0.6861639951109668
for epoch:16 loss is 0.685713850672605
for epoch:17 loss is 0.6852839913272798
for epoch:18 loss is 0.6848728443266924
for epoch:19 loss is 0.6844789818651296
for epoch:20 loss is 0.6841011066532824
for epoch:21 loss is 0.6837380390274822
for epoch:22 loss is 0.6833887054168651
for epoch:23 loss is 0.6830521280138913
for epoch:24 loss is 0.6827274155131856
for epoch:25 loss is 0.6824137548004122


In [ ]:
with torch.no_grad():
    ypred=model.forwad(x_test_tensor)
    ypred=(ypred>0.5).float()
    accuracy=(ypred==y_test_tensor).float().mean(